# Generated by Django 3.2.13 on 2022-09-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(db_column='age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(db_column='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prk',
            field=models.IntegerField(db_column='prk', primary_key=True, serialize=False),
        ),
    ]
