# Generated by Django 4.1 on 2022-09-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientexam", name="age", field=models.CharField(max_length=45),
        ),
    ]
