# Generated by Django 4.1 on 2022-09-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_delete_authgroup_delete_authgrouppermissions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientHosp",
            fields=[
                ("prk", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
                ("age", models.CharField(blank=True, max_length=3, null=True)),
                ("asfaleia", models.CharField(blank=True, max_length=45, null=True)),
                ("energeia", models.CharField(blank=True, max_length=45, null=True)),
                ("datein", models.CharField(blank=True, max_length=45, null=True)),
                ("dateout", models.CharField(blank=True, max_length=45, null=True)),
                ("personal_patient", models.IntegerField(blank=True, null=True)),
                ("istoriko", models.CharField(blank=True, max_length=45, null=True)),
                ("gnomateusi", models.CharField(blank=True, max_length=45, null=True)),
                ("odigies", models.CharField(blank=True, max_length=45, null=True)),
                ("cost", models.CharField(blank=True, max_length=45, null=True)),
                ("payment", models.CharField(blank=True, max_length=45, null=True)),
                ("amka", models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={"db_table": "patient_hosp", "managed": False,},
        ),
    ]
