# Generated by Django 3.2.13 on 2022-09-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_patienthosp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_cost',
            fields=[
                ('code_exam', models.AutoField(primary_key=True, serialize=False)),
                ('cost_exam', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'exam_cost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('code_exam', models.AutoField(primary_key=True, serialize=False)),
                ('exam', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'exams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('code_ins', models.AutoField(primary_key=True, serialize=False)),
                ('insurance', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'insurance',
                'managed': False,
            },
        ),
    ]
