# Generated by Django 4.1.1 on 2022-10-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_exam_cost_exams_insurance"),
    ]

    operations = [
        migrations.CreateModel(
            name="lifecheck",
            fields=[
                ("prk", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
                ("date_birth", models.CharField(blank=True, max_length=45, null=True)),
                ("date_exam", models.CharField(blank=True, max_length=45, null=True)),
                ("istoriko", models.CharField(blank=True, max_length=45, null=True)),
                ("gnomateusi", models.CharField(blank=True, max_length=45, null=True)),
                ("odigies", models.CharField(blank=True, max_length=45, null=True)),
                ("cost", models.CharField(blank=True, max_length=45, null=True)),
                ("amka", models.CharField(blank=True, max_length=11, null=True)),
                ("gender", models.CharField(blank=True, max_length=45, null=True)),
                ("exam_file", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "private_patient",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
            ],
            options={"db_table": "lifecheck", "managed": False,},
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
