# Generated by Django 3.2.14 on 2022-12-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'managed': False},
        ),
    ]
