# Generated by Django 3.2.14 on 2022-12-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_events_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='events',
        ),
    ]
